### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by DorisAmoakohene** [DorisAmoakohene/Codes-and-Test-for-my-paper#3]
@tdhock

See graphs to show for performance testing for your review

![atime list 5427](https://github.com/user-attachments/assets/0736ae3e-f5ea-488f-b34d-8da6561f737c)

![atime list 4200](https://github.com/user-attachments/assets/e0b7c35f-2b86-4bc0-8f06-d193f37276b7)

**Comment by tdhock** [comment]
please change slow to Slow (capital S)

please use colors from atime_pkg, https://github.com/DorisAmoakohene/Codes-and-Test-for-my-paper/issues/4#issuecomment-2258077652

**Comment by tdhock** [comment]
please remove x axis ticks larger than data range (1e9, 1e5)

please clarify x axis title -- what is data size? (rows, columns, etc?)

**Comment by DorisAmoakohene** [comment]
![atime list 4200](https://github.com/user-attachments/assets/c9d1ff37-f9ca-41f6-8c70-3c4819c14947)
![atime list 5427](https://github.com/user-attachments/assets/9112e223-e6fb-4624-a9a7-c38fe02218d4)

**Comment by tdhock** [comment]
please increase the number of grid points
`10^seq(1,7,by=0.25)` instead of by=1
please remove 1e8 tick which is outside of data range

**Comment by DorisAmoakohene** [comment]
when I remove tick 1e8 it makes the text size of the fast and slow small

**Comment by tdhock** [comment]
I understand that you have reduced the range of the x axis from 1e8 and that makes the text size of the direct labels too small. 
I did not suggest to reduce the range. Keep the same range, and remove the 1e8 tick, by using `scale_x_log10(limits=c(1e1,1e8), breaks=10^seq(1, 7))` etc
