### ISSUE TITLE
Continuous Performance Testing/GitHub Action

### ISSUE THREAD

**Issue by DorisAmoakohene** [DorisAmoakohene/Codes-and-Test-for-my-paper#4]
@tdhock

Kindly review this for me to include in my paper for the GitHub section

![GitHub action test](https://github.com/user-attachments/assets/187e9f22-5465-4936-88ae-6bda420aa843)

**Comment by tdhock** [comment]
BASE should be lower-case, base as documented here https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request

please change Head to HEAD as documented here https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefHEADaHEAD

please use same colors as atime_pkg, here https://github.com/tdhock/atime/blob/main/R/versions.R#L233
```r
    c(#RColorBrewer::brewer.pal(7, "Dark2")
      HEAD="#1B9E77",
      base="#D95F02",
      "merge-base"="#7570B3",
      CRAN="#E7298A",
      Before="#66A61E",
      Regression="#E6AB02", Slow="#E6AB02",
      Fixed="#A6761D", Fast="#A6761D"
    )
```

**Comment by tdhock** [comment]
please use alpha=0.5 for geom_ribbon and add geom_line for median

please remove tick marks which are beyond range of the data (1e8)

**Comment by tdhock** [comment]
please show a screenshot of the figure in context of its caption, so we can see if the figure text size is about the same as the caption text size.

**Comment by DorisAmoakohene** [comment]
![GitHub action test](https://github.com/user-attachments/assets/55071a08-0a74-4045-9bed-60156830bf4f)



I will send the screenshot soon, could you verify if everything is fine before I include in the docs and send the screenshot

**Comment by tdhock** [comment]
yes that looks better
